#!/usr/bin/python3

import lib_gs as gs
import pandas as pd
import json

SHEET_ID = "needs_to_be_filled"

def main():
    """
    Read the file generated by the script, fetch and push to the sheet.
    """
    
    # Create /tmp/output.log first
    # for RESOURCE in $(oc api-resources -o name | sort); do oc get --ignore-not-found $RESOURCE -A -o json 2>/dev/null | jq -rc '.items[] | select(.metadata.labels["hive.openshift.io/managed"] == "true") | {kind: .kind, namespace: .metadata.namespace, name: .metadata.name}'; done | tee /tmp/output.log
    data = open("/tmp/output.log", 'r')
    lines = data.readlines()
    template = pd.DataFrame(columns=('NAMESPACE', 'KIND', 'NAME'))
    
    for line in lines:
        source = json.loads(line)
        template.loc[len(template)] = [source["namespace"], source["kind"], source["name"]]

    # sort
    template = template.sort_values(by=['NAMESPACE', 'KIND', 'NAME'])
    # update the excel
    gs.update_sheet([SHEET_ID], 'Managed Resources', template)
    
    # If we wanna debug what's gonna be written to the excel, we can print out the whole template to console.
    print(template)

if __name__ == "__main__":
    main()

